name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [1.6.18, 1.4.8, 1.2.18]
        toolchain:
          - stable
          # - beta
          # - nightly

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install Nim
      uses: asdf-vm/actions/install@v3
      with:
        tool_versions: |
          nim ${{ matrix.nim }}

    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
